CREATE TABLE IF NOT EXISTS payment_refund_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_refund_id VARCHAR(128) NOT NULL,
    amount VARCHAR(32) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL,
    refund_quota BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    reason TEXT NOT NULL,
    actor_user_id BIGINT UNSIGNED NOT NULL,
    request_id VARCHAR(128),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3),
    INDEX idx_payment_refund_requests_order_no (order_no),
    INDEX idx_payment_refund_requests_user_id (user_id),
    INDEX idx_payment_refund_requests_provider (provider),
    INDEX idx_payment_refund_requests_provider_refund_id (provider_refund_id),
    INDEX idx_payment_refund_requests_status (status),
    INDEX idx_payment_refund_requests_actor_user_id (actor_user_id),
    UNIQUE INDEX idx_payment_refund_requests_idempotency_key (idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
