CREATE TABLE IF NOT EXISTS alert_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(128) NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'warning',
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    user_id BIGINT UNSIGNED,
    token_id BIGINT UNSIGNED,
    title VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    details_json JSON,
    acked_at DATETIME(3),
    acked_by_user_id BIGINT UNSIGNED,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3),
    INDEX idx_alert_events_type (type),
    INDEX idx_alert_events_severity (severity),
    INDEX idx_alert_events_status (status),
    INDEX idx_alert_resource (resource_type, resource_id),
    INDEX idx_alert_events_user_id (user_id),
    INDEX idx_alert_events_token_id (token_id),
    INDEX idx_alert_events_acked_by_user_id (acked_by_user_id),
    INDEX idx_alert_events_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
